{
 "title": "Ret Hat Operators",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{namespace !~ \"openshift-.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RHT Operators: CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage (millicores)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace =~ \"$namespace\", pod !=\"\"}) by (pod, namespace)*1000 * on (pod) group_left(label_rht_subcomp_t, label_rht_comp) kube_pod_labels{label_rht_subcomp_t =~ \"application|infrastructure\", pod !=\"\"}",
       "legendFormat": "{{label_rht_comp}} / {{namespace}} -- {{ pod }}"
      }
     ]
    },
    {
     "title": "Requests (millicores)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{resource=\"cpu\", namespace =~ \"$namespace\", pod !=\"\"}*1000 * on (pod) group_left(label_rht_subcomp_t, label_rht_comp) kube_pod_labels{label_rht_subcomp_t =~ \"application|infrastructure\", pod !=\"\"}",
       "legendFormat": "{{label_rht_comp}} / {{namespace}} -- {{ pod }}"
      }
     ]
    },
    {
     "title": "Limits (millicores)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\", namespace =~ \"$namespace\", pod !=\"\"}*1000 * on (pod) group_left(label_rht_subcomp_t, label_rht_comp) kube_pod_labels{label_rht_subcomp_t =~ \"application|infrastructure\", pod !=\"\"}",
       "legendFormat": "{{label_rht_comp}} / {{namespace}} -- {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RHT Operators: MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace =~ \"$namespace\", pod !=\"\"}) by (pod, namespace) * on (pod) group_left(label_rht_subcomp_t, label_rht_comp) kube_pod_labels{label_rht_subcomp_t =~ \"application|infrastructure\", pod !=\"\"}",
       "legendFormat": "{{label_rht_comp}} / {{namespace}} -- {{ pod }}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{resource=\"memory\", namespace =~ \"$namespace\", pod !=\"\"} * on (pod) group_left(label_rht_subcomp_t, label_rht_comp) kube_pod_labels{label_rht_subcomp_t =~ \"application|infrastructure\", pod !=\"\"}",
       "legendFormat": "{{label_rht_comp}} / {{namespace}} -- {{ pod }}"
      }
     ]
    },
    {
     "title": " Limits",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{resource=\"memory\", namespace =~ \"$namespace\", pod !=\"\"} * on (pod) group_left(label_rht_subcomp_t, label_rht_comp) kube_pod_labels{label_rht_subcomp_t =~ \"application|infrastructure\", pod !=\"\"}",
       "legendFormat": "{{label_rht_comp}} / {{namespace}} -- {{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}