{{- range $promDataSource := .Values.grafanaDataSources.prometheus }}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ $promDataSource.name | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana
    operator: grafana
spec:
  datasources:
    - access: proxy
      editable: true
      secureJsonData:
        httpHeaderValue1: >-
          Bearer
          {{ $promDataSource.auth.bearerToken }}
      name: {{ $promDataSource.name | lower }}
      url: {{ $promDataSource.auth.url | squote}}
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      isDefault: false
      version: 1
      type: prometheus
  name: {{ $promDataSource.name | lower }}
---
{{- end }}
